services:
  doorman:
    image: duro-doorman:latest
    ports:
      - 4000:4000
    env_file:
      - ./.env_docker
    depends_on:
      - db
      - queue

  frontend:
    image: duro-butler:latest
    ports:
      - 5000:5000
    env_file:
      - ./apps/provider/.env
      
  queue:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
            
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

