name: duro by team kapppa
run-name: ${{ github.actor }} 
on: [push]
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: run build
        env:
          NEXT_PUBLIC_API_URL: https://duro-be.onrender.com
        run: pnpm run build

      - name: start projects
        env:
          NEXT_PUBLIC_API_URL: https://duro-be.onrender.com
        run: pnpm run start:fe &

      - name: run tests
        run: pnpm run test:ci

