name: duro by team kapppa
run-name: ${{ github.actor }} 
on: [push]
jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: pnpm run build
          start: pnpm  start
          wait-on: "http://localhost:3000"
          component: true
